version: '3.8'

services:
  calendar-color-mcp:
    build: .
    container_name: calendar-color-mcp
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEBUG=${DEBUG:-false}
    volumes:
      # Persist user tokens between container restarts
      - ./user_tokens:/app/user_tokens
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    restart: unless-stopped
    # Use host network mode for MCP communication
    network_mode: host
    stdin_open: true
    tty: true

  # Development service with volume mounts for live reloading
  calendar-color-mcp-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: calendar-color-mcp-dev
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEBUG=true
      - RACK_ENV=development
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    working_dir: /app
    network_mode: host
    stdin_open: true
    tty: true
    profiles:
      - dev

volumes:
  bundle_cache: